---
deployment:
  tasks:
    - export DEPLOYPATH=/home/creativedoran/creative.doran.com
    - /bin/rsync -a --exclude='.git' --exclude='node_modules' --exclude='tests' $cpanel_source_dir/ $DEPLOYPATH
