"use client";

import { useState } from "react";
import { Navbar, type NavbarSession, type NavbarVariant } from "@/design-system/organisms/navigation/navbar";

export function NavbarDocumentation() {
  const [variant, setVariant] = useState<NavbarVariant>("light");
  const [session, setSession] = useState<Exclude<NavbarSession, "connected">>("preview-authenticated");
  const [sticky, setSticky] = useState(false);
  const [viewport, setViewport] = useState<"desktop" | "mobile">("desktop");

  return <article className="space-y-8"><header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cu-muted">Design System / Organisms</p><h1 className="mt-2 text-3xl font-bold text-cu-ink">Navbar</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-cu-muted">Navbar utama Creative Universe. Playground ini menjadi sumber visual untuk mengontrol dan memverifikasi variant tanpa halaman demo terpisah.</p></header>
    <section className="rounded-2xl border border-cu-line bg-cu-surface p-5"><h2 className="text-lg font-semibold text-cu-ink">Control panel</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Control label="Variant" value={variant} options={["light","dark","transparent-dark"]} onChange={(v) => setVariant(v as NavbarVariant)} /><Control label="Session" value={session} options={["preview-authenticated","guest"]} onChange={(v) => setSession(v as typeof session)} /><Control label="Position" value={sticky ? "sticky" : "relative"} options={["relative","sticky"]} onChange={(v) => setSticky(v === "sticky")} /><Control label="Viewport" value={viewport} options={["desktop","mobile"]} onChange={(v) => setViewport(v as typeof viewport)} /></div></section>
    <section><div className="mb-3 flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-cu-ink">Live preview</h2><code className="rounded bg-cu-panel-soft px-2 py-1 text-xs text-cu-muted">{`<Navbar variant="${variant}" sticky={${sticky}} />`}</code></div><div className="overflow-x-auto rounded-2xl border border-cu-line bg-[#e9ebef] p-4"><div className={`mx-auto min-h-64 overflow-visible bg-white shadow-sm transition-[width] ${viewport === "mobile" ? "w-[390px] max-w-full" : "w-full min-w-[720px]"}`}><Navbar variant={variant} sticky={sticky} session={session} /><div className="p-6 text-sm text-gray-400">Area halaman untuk menguji posisi, kontras, dropdown aplikasi, dan menu akun.</div></div></div></section>
    <section><h2 className="text-lg font-semibold text-cu-ink">Variant matrix</h2><div className="mt-3 overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead><tr className="border-b border-cu-line"><th className="p-3">Axis</th><th className="p-3">Values</th><th className="p-3">Contract</th></tr></thead><tbody><Row axis="Visual" values="light, dark, transparent-dark" contract="Transparent-dark memakai seluruh foreground dark dengan permukaan transparan." /><Row axis="Position" values="sticky, relative" contract="Sticky default produksi; relative untuk layout khusus." /><Row axis="Session" values="guest, authenticated" contract="Guest hanya logo; authenticated menampilkan seluruh action." /><Row axis="Viewport" values="desktop, mobile" contract="Satu organism responsif; popup aplikasi fixed pada mobile." /></tbody></table></div><p className="mt-3 text-sm text-cu-muted">Total kontrak kombinatorial: 3 × 2 × 2 = <strong>12 variant perilaku</strong>. Viewport adalah mode pengujian responsif, bukan prop produksi.</p></section>
    <section><h2 className="text-lg font-semibold text-cu-ink">Atomic anatomy</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-cu-muted"><li><strong>Atoms:</strong> CreativeUniverseLogo, NavbarAction, NavbarAvatar.</li><li><strong>Molecules:</strong> NavbarMenuItem, NavbarUserSummary.</li><li><strong>Organism:</strong> Navbar—auth, dropdown, applications, notifications, messages, dan logout.</li><li><strong>Template:</strong> NavbarDocumentation—control panel dan visual verification surface.</li></ol></section>
    <section><h2 className="text-lg font-semibold text-cu-ink">Functional contract</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-cu-muted"><li>Dropdown menutup saat klik di luar atau menekan Escape.</li><li>Aplikasi berasal dari registry user dan mempertahankan badge eksperimen.</li><li>Developer Panel hanya terlihat untuk Root.</li><li>Notifikasi, pesan, profil, settings, documentation, dan logout tetap tersedia.</li><li>Mode preview tidak menjalankan realtime request atau logout nyata.</li></ul></section>
  </article>;
}

function Control({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="flex flex-col gap-1.5 text-xs font-semibold text-cu-muted">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-xl border border-cu-line bg-white px-3 text-sm font-medium text-cu-ink outline-none focus:border-cu-focus">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Row({ axis, values, contract }: { axis: string; values: string; contract: string }) { return <tr className="border-b border-cu-line/70"><td className="p-3 font-semibold text-cu-ink">{axis}</td><td className="p-3 font-mono text-xs text-cu-muted">{values}</td><td className="p-3 text-cu-muted">{contract}</td></tr>; }
