"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/providers/auth-provider";
import { ValidationError } from "@/core/api/client";
import AuthCard from "./AuthCard/AuthCard";
import { ParallaxBackground } from "@/components/universe/Background/ParallaxBackground";

export default function LoginPage() { const { login } = useAuth(); const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const user = await login({ username: username.trim(), password }); const redirect = new URLSearchParams(window.location.search).get("redirect"); router.replace(user.is_onboarded ? redirect || "/" : "/onboarding"); } catch (cause) { setError(cause instanceof ValidationError ? Object.values(cause.errors).flat()[0] ?? "Data login tidak valid." : cause instanceof Error ? cause.message : "Login gagal."); setBusy(false); } } return <main className="cu-style relative flex min-h-screen items-center justify-center overflow-hidden bg-[#16001f] px-4 py-10"><ParallaxBackground /><AuthCard title="Masuk" footerText="Butuh bantuan? Buka Help Center"><div className="p-8"><div className="mb-6 text-center"><h1 className="text-3xl font-semibold">Masuk</h1><p className="mt-2 text-sm text-slate-500">Masuk ke Creative Universe</p></div>{error && <p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="flex flex-col gap-5"><label className="block text-sm font-medium">Username<input className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2" value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" required /></label><label className="relative block text-sm font-medium">Password<input className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 pr-11" type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /><button type="button" className="absolute right-3 top-8 text-slate-500" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Sembunyikan password" : "Tampilkan password"}><span className="material-symbols-rounded">{showPassword ? "visibility_off" : "visibility"}</span></button></label><button className="mt-2 w-full rounded-full bg-slate-900 px-4 py-3 font-medium text-white disabled:opacity-60" disabled={busy}>{busy ? "Memproses..." : "Masuk"}</button></form><Link className="mt-5 block text-center text-sm text-sky-700" href="/forgot-password">Lupa password?</Link></div></AuthCard></main>; }

