"use client";

import { FormEvent } from "react";
import { MaterialIcon } from "@/components/ui/material-icon";

export function PreferenceToggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-cu-line bg-cu-panel-soft/50 p-4"><span><span className="block text-sm font-medium text-cu-ink">{label}</span><span className="mt-1 block text-xs text-cu-muted">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 shrink-0 rounded border-cu-line text-cu-ink" /></label>;
}

type PreferenceProps = {
  notificationInApp: boolean; notificationWhatsapp: boolean; notificationTaskUpdates: boolean; notificationMentions: boolean; notificationDeadlines: boolean; quietStart: string; quietEnd: string;
  setNotificationInApp: (value: boolean) => void; setNotificationWhatsapp: (value: boolean) => void; setNotificationTaskUpdates: (value: boolean) => void; setNotificationMentions: (value: boolean) => void; setNotificationDeadlines: (value: boolean) => void; setQuietStart: (value: string) => void; setQuietEnd: (value: string) => void;
  isSaving: boolean; status: string | null; error: string | null; onSave: (settings: Record<string, unknown>, message: string) => void;
};

export function NotificationsTab(props: PreferenceProps) {
  const { notificationInApp, notificationWhatsapp, notificationTaskUpdates, notificationMentions, notificationDeadlines, quietStart, quietEnd, setNotificationInApp, setNotificationWhatsapp, setNotificationTaskUpdates, setNotificationMentions, setNotificationDeadlines, setQuietStart, setQuietEnd, isSaving, status, error, onSave } = props;
  const submit = (event: FormEvent) => { event.preventDefault(); onSave({ notification_in_app: notificationInApp, notification_whatsapp: notificationWhatsapp, notification_task_updates: notificationTaskUpdates, notification_mentions: notificationMentions, notification_deadlines: notificationDeadlines, notification_quiet_start: quietStart || null, notification_quiet_end: quietEnd || null }, "Preferensi notifikasi berhasil disimpan."); };
  return <form onSubmit={submit} className="space-y-6 animate-fade-in"><div className="border-b border-cu-line pb-3"><h2 className="text-2xl font-semibold text-cu-ink">Notifikasi</h2><p className="mt-1 text-sm text-cu-muted">Preferensi ini disimpan terlebih dahulu. Pengiriman WhatsApp per-event akan diaktifkan saat integrasinya siap.</p></div>{status && <p className="rounded-lg border border-cu-success/20 bg-cu-success-soft p-4 text-sm text-cu-success">{status}</p>}{error && <p className="rounded-lg border border-cu-danger/20 bg-cu-danger-soft p-4 text-sm text-cu-danger">{error}</p>}<div className="space-y-3 rounded-2xl border border-cu-line bg-cu-surface p-5"><PreferenceToggle label="Notifikasi dalam aplikasi" description="Tampilkan notifikasi pada Creative Universe." checked={notificationInApp} onChange={setNotificationInApp} /><PreferenceToggle label="Notifikasi WhatsApp" description="Simpan preferensi kanal WhatsApp untuk integrasi berikutnya." checked={notificationWhatsapp} onChange={setNotificationWhatsapp} /></div><div className="space-y-3 rounded-2xl border border-cu-line bg-cu-surface p-5"><h3 className="text-sm font-semibold text-cu-ink">Peristiwa yang ingin diterima</h3><PreferenceToggle label="Update tugas" description="Task baru, perubahan status, dan assignment." checked={notificationTaskUpdates} onChange={setNotificationTaskUpdates} /><PreferenceToggle label="Mention dan pesan" description="Saat Anda disebut atau menerima aktivitas percakapan." checked={notificationMentions} onChange={setNotificationMentions} /><PreferenceToggle label="Deadline" description="Pengingat tenggat waktu dan keterlambatan." checked={notificationDeadlines} onChange={setNotificationDeadlines} /></div><div className="rounded-2xl border border-cu-line bg-cu-surface p-5"><h3 className="text-sm font-semibold text-cu-ink">Jam hening</h3><p className="mt-1 text-xs text-cu-muted">Disimpan sebagai preferensi untuk aturan pengiriman mendatang.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-cu-ink">Mulai<input type="time" value={quietStart} onChange={(event) => setQuietStart(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-cu-line bg-cu-surface px-3 py-2" /></label><label className="text-sm font-medium text-cu-ink">Selesai<input type="time" value={quietEnd} onChange={(event) => setQuietEnd(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-cu-line bg-cu-surface px-3 py-2" /></label></div></div><button type="submit" disabled={isSaving} className="inline-flex h-10 items-center justify-center rounded-full bg-cu-ink px-5 text-sm font-medium text-cu-surface disabled:opacity-50">{isSaving ? "Menyimpan..." : "Simpan Preferensi"}</button></form>;
}

export function PrivacyTab({ checked, onChange, isSaving, status, error, onSave }: { checked: boolean; onChange: (value: boolean) => void; isSaving: boolean; status: string | null; error: string | null; onSave: (settings: Record<string, unknown>, message: string) => void }) {
  return <form onSubmit={(event) => { event.preventDefault(); onSave({ profile_show_applications: checked }, "Preferensi privasi berhasil disimpan."); }} className="space-y-6 animate-fade-in"><div className="border-b border-cu-line pb-3"><h2 className="text-2xl font-semibold text-cu-ink">Privasi Profil</h2><p className="mt-1 text-sm text-cu-muted">Atur informasi profil yang boleh ditampilkan kepada pengguna lain.</p></div>{status && <p className="rounded-lg border border-cu-success/20 bg-cu-success-soft p-4 text-sm text-cu-success">{status}</p>}{error && <p className="rounded-lg border border-cu-danger/20 bg-cu-danger-soft p-4 text-sm text-cu-danger">{error}</p>}<div className="rounded-2xl border border-cu-line bg-cu-surface p-5"><PreferenceToggle label="Tampilkan daftar aplikasi saya" description="Izinkan daftar aplikasi yang Anda akses terlihat pada profil pengguna lain." checked={checked} onChange={onChange} /></div><button type="submit" disabled={isSaving} className="inline-flex h-10 items-center justify-center rounded-full bg-cu-ink px-5 text-sm font-medium text-cu-surface disabled:opacity-50">{isSaving ? "Menyimpan..." : "Simpan Privasi"}</button></form>;
}

export function ApplicationsTab({ applications }: { applications: Array<{ key: string; type: string; sort_order: number; display_name: string; status: string }> }) {
  const items = applications.filter((application) => application.type === "sub_app").sort((left, right) => left.sort_order - right.sort_order);
  return <div className="space-y-6 animate-fade-in"><div className="border-b border-cu-line pb-3"><h2 className="text-2xl font-semibold text-cu-ink">Aplikasi Saya</h2><p className="mt-1 text-sm text-cu-muted">Akses aplikasi dikelola administrator. Landing setelah login tetap berada di halaman utama.</p></div><div className="grid gap-3 sm:grid-cols-2">{items.map((application) => <div key={application.key} className="rounded-2xl border border-cu-line bg-cu-surface p-5"><MaterialIcon name="apps" size="sm" className="text-cu-muted" /><h3 className="mt-3 text-sm font-semibold text-cu-ink">{application.display_name}</h3><p className="mt-1 text-xs text-cu-muted">{application.status === "experimental" ? "Eksperimen" : "Aktif"}</p></div>)}{items.length === 0 && <p className="text-sm text-cu-muted">Belum ada aplikasi yang dapat diakses.</p>}</div></div>;
}

export function BillingTab({ tab }: { tab: string }) {
  const title = { billing_overview: "Billing Overview", billing_usage: "Billing Usage", billing_ai: "AI Usage Settings", billing_budgets: "Budgets and Alerts" }[tab] || "Billing";
  return <div className="space-y-6 animate-fade-in"><div className="border-b border-cu-line pb-3"><h2 className="text-2xl font-semibold text-cu-ink">{title}</h2></div><div className="rounded-2xl border border-cu-line bg-cu-surface p-5 text-sm text-cu-muted">Ini adalah konten halaman demo untuk menu bertingkat (nested menu) &quot;Billing and licensing&quot;.</div></div>;
}
