"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { authApi, type OnboardingDivision } from "@/core/auth";
import { ValidationError } from "@/core/api/client";
import { useAuth } from "@/providers/auth-provider";

export default function OnboardingPage() {
  const { user, refreshUser } = useAuth(); const router = useRouter(); const [divisions, setDivisions] = useState<OnboardingDivision[]>([]); const [name, setName] = useState(user?.name ?? ""); const [divisionId, setDivisionId] = useState(""); const [positionId, setPositionId] = useState(""); const [positionName, setPositionName] = useState(""); const [whatsapp, setWhatsapp] = useState(user?.whatsapp_number ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (user?.is_onboarded) router.replace("/"); }, [user, router]);
  useEffect(() => { void authApi.onboarding.data().then(setDivisions).catch(() => setError("Data onboarding gagal dimuat.")); }, []);
  const selected = divisions.find((division) => String(division.id) === divisionId);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await authApi.onboarding.submit({ name: name.trim(), division_id: Number(divisionId), whatsapp_number: whatsapp.trim(), ...(positionId ? { position_id: Number(positionId) } : { position_name: positionName.trim() }) }); await refreshUser(); router.replace("/"); } catch (cause) { setError(cause instanceof ValidationError ? Object.values(cause.errors).flat()[0] ?? "Data belum valid." : cause instanceof Error ? cause.message : "Onboarding gagal."); } finally { setBusy(false); } }
  return <main className="cu-style flex min-h-screen items-center justify-center bg-sky px-4 py-10"><section className="w-full max-w-lg rounded-3xl bg-white p-8 text-slate-900"><h1 className="text-2xl font-semibold">Lengkapi profil</h1><p className="mt-2 text-sm text-slate-500">Lengkapi data sebelum masuk ke Universe.</p>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><input className="w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Nama lengkap" value={name} onChange={(event) => setName(event.target.value)} required /><select className="w-full rounded-lg border border-slate-300 px-3 py-2" value={divisionId} onChange={(event) => { setDivisionId(event.target.value); setPositionId(""); }} required><option value="">Pilih divisi</option>{divisions.map((division) => <option key={division.id} value={division.id}>{division.name}</option>)}</select>{selected && <select className="w-full rounded-lg border border-slate-300 px-3 py-2" value={positionId} onChange={(event) => setPositionId(event.target.value)}><option value="">Pilih posisi atau isi custom</option>{selected.positions.map((position) => <option key={position.id} value={position.id}>{position.name}</option>)}</select>}<input className="w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Posisi custom (opsional)" value={positionName} onChange={(event) => setPositionName(event.target.value)} /><input className="w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Nomor WhatsApp" value={whatsapp} onChange={(event) => setWhatsapp(event.target.value)} required /><button className="w-full rounded-full bg-slate-900 px-4 py-3 text-white disabled:opacity-60" disabled={busy}>{busy ? "Menyimpan..." : "Simpan dan lanjutkan"}</button></form></section></main>;
}
