"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { authApi } from "@/core/auth";
import { ValidationError } from "@/core/api/client";

type Step = "request" | "verify" | "reset";
export default function ForgotPasswordPage() {
  const router = useRouter(); const [step, setStep] = useState<Step>("request"); const [login, setLogin] = useState(""); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [masked, setMasked] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [resendIn, setResendIn] = useState(0);
  useEffect(() => { if (!resendIn) return; const timer = window.setInterval(() => setResendIn((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [resendIn]);
  async function run(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { if (step === "request") { const result = await authApi.passwordReset.requestOtp(login); setMasked(result.masked_phone || "WhatsApp Anda"); setStep("verify"); setResendIn(60); } else if (step === "verify") { await authApi.passwordReset.verifyOtp(otp); setStep("reset"); } else { await authApi.passwordReset.reset(password, confirmation); router.replace("/login?reset=success"); } } catch (cause) { setError(cause instanceof ValidationError ? Object.values(cause.errors).flat()[0] ?? "Data tidak valid." : cause instanceof Error ? cause.message : "Permintaan gagal."); } finally { setBusy(false); } }
  const title = step === "request" ? "Lupa Password" : step === "verify" ? "Verifikasi OTP" : "Password Baru";
  return <main className="cu-style flex min-h-screen items-center justify-center bg-sky px-4 py-10"><section className="w-full max-w-md rounded-3xl bg-white p-8 text-slate-900"><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm text-slate-500">{step === "request" ? "Masukkan email atau username." : step === "verify" ? `Kode dikirim ke ${masked}.` : "Buat password baru."}</p>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={run} className="mt-6 space-y-4">{step === "request" && <input className="w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Email atau username" value={login} onChange={(event) => setLogin(event.target.value)} required />}{step === "verify" && <input className="w-full rounded-lg border border-slate-300 px-3 py-2 text-center tracking-widest" maxLength={6} placeholder="000000" value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, ""))} required />}{step === "reset" && <><input className="w-full rounded-lg border border-slate-300 px-3 py-2" type="password" placeholder="Password baru" value={password} onChange={(event) => setPassword(event.target.value)} required /><input className="w-full rounded-lg border border-slate-300 px-3 py-2" type="password" placeholder="Ulangi password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} required /></>}<button className="w-full rounded-full bg-slate-900 px-4 py-3 text-white disabled:opacity-60" disabled={busy}>{busy ? "Memproses..." : step === "request" ? "Kirim Kode OTP" : step === "verify" ? "Verifikasi" : "Simpan Password"}</button></form><Link className="mt-5 block text-center text-sm text-sky-700" href="/login">Kembali ke login</Link></section></main>;
}
